test_size: 0.2
random_state: 42

pipe = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("selectkbest", SelectKBest()),
    ("classifier", RandomForestClassifier())])

GridSearchCV:
  estimator: pipe
  param_grid:
     'scaler': [StandardScaler(), None],
    'selectkbest__k':np.arange(10,20),
    'classifier': [GradientBoostingClassifier()],
    'classifier__max_depth': [7,9,11]
  cv: 5
  scoring: recall